#if !canImport(ObjectiveC)
import XCTest

extension IndentationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndentationTests = [
        ("testSpaceTabs", testSpaceTabs),
        ("testTabs", testTabs),
    ]
}

extension SwiftArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftArrayTests = [
        ("testInitializing", testInitializing),
    ]
}

extension SwiftClassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftClassTests = [
        ("testInitializing", testInitializing),
    ]
}

extension SwiftFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftFileTests = [
        ("testInitializing", testInitializing),
    ]
}

extension SwiftFunctionBodyExpressionArgumentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftFunctionBodyExpressionArgumentTests = [
        ("testInitializing", testInitializing),
    ]
}

extension SwiftFunctionBodyExpressionCallTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftFunctionBodyExpressionCallTests = [
        ("testInitializing", testInitializing),
        ("testInitializingWithChildExpression", testInitializingWithChildExpression),
    ]
}

extension SwiftFunctionBodyLocalVarAssignmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftFunctionBodyLocalVarAssignmentTests = [
        ("testInitializing", testInitializing),
    ]
}

extension SwiftFunctionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftFunctionTests = [
        ("testInitializingInvalidAttribute", testInitializingInvalidAttribute),
        ("testInitializingOverrideInit", testInitializingOverrideInit),
        ("testInitializingRequiredOptionalInit", testInitializingRequiredOptionalInit),
        ("testInitializinInternalOverride", testInitializinInternalOverride),
        ("testInitializinNoReturnNoBody", testInitializinNoReturnNoBody),
    ]
}

extension SwiftWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftWriterTests = [
        ("testGenerateClassDeclaration", testGenerateClassDeclaration),
        ("testGenerateFunctionDeclaration", testGenerateFunctionDeclaration),
        ("testGenerateHeaderAndImports", testGenerateHeaderAndImports),
        ("testGenerateVariableAssignment", testGenerateVariableAssignment),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IndentationTests.__allTests__IndentationTests),
        testCase(SwiftArrayTests.__allTests__SwiftArrayTests),
        testCase(SwiftClassTests.__allTests__SwiftClassTests),
        testCase(SwiftFileTests.__allTests__SwiftFileTests),
        testCase(SwiftFunctionBodyExpressionArgumentTests.__allTests__SwiftFunctionBodyExpressionArgumentTests),
        testCase(SwiftFunctionBodyExpressionCallTests.__allTests__SwiftFunctionBodyExpressionCallTests),
        testCase(SwiftFunctionBodyLocalVarAssignmentTests.__allTests__SwiftFunctionBodyLocalVarAssignmentTests),
        testCase(SwiftFunctionTests.__allTests__SwiftFunctionTests),
        testCase(SwiftWriterTests.__allTests__SwiftWriterTests),
    ]
}
#endif
